name: Deploy Azure Function

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: api
        run: npm install

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: alice-cloud-counter
          package: ./api
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
