name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload index.html
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload \
              --account-name simplyaliceportfolio \
              --container-name '$web' \
              --name index.html \
              --file index.html \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --overwrite

      - name: Upload assets folder
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name simplyaliceportfolio \
              --destination '$web/assets' \
              --source assets \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --overwrite
